### ISSUE TITLE
Write Data to Google Fit

### ISSUE THREAD

**Issue by milandzuris** [YorkshireIoT/ha-google-fit#183] opened 2024-02-06 17:06 UTC
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/YorkshireIoT/ha-google-fit/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Hi, is possible write data to Google Fit?, i have Xiaomi Personal Weight and i like write data to Fit from HA
https://www.lprp.fr/2021/02/xiaomi-smart-scale-with-domoticz-nodered-raspberry-and-google-fit/

### Describe the solution you'd like

*

### Describe alternatives you've considered

*

### Additional context

*

**Comment by YorkshireIoT** [comment] 2024-02-07 10:36
Duplicate of #108

**Closed by YorkshireIoT** 2024-02-07 10:36 UTC
